name: qe-lectures
channels:
  - default
  - conda-forge
dependencies:
  - python
  - jupyter
  - jupyterlab
  - nbconvert
  - pytest
  - pytest-xdist
  - pytest-cov
  - codecov
  - pre-commit
  - pylint
  - flake8
  - black
  - autopep8
  - pip
  - setuptools
  - pandoc
  - pandas
  - numba
  - numpy
  - sphinx
  - pip
  - pip:
    - sphinxcontrib-jupyter
    - sphinxcontrib-bibtex
    - quantecon
    - joblib
