name: Tests
on: [pull_request]

jobs:
  setup:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda ${{ matrix.python-version}}
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: qe-lectures
      - name: Get Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Run Execution Tests
        shell: bash -l {0}
        run: bash scripts/execution-test.sh "${{ steps.files.outputs.all }}"
      - name: Run Linkchecker
        shell: bash -l {0}
        run: bash scripts/linkchecker-test.sh