name: Tests
on: [push]

jobs:
  setup:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda ${{ matrix.python-version}}
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: qe-lectures
      - name: Changed Files Exporter
        uses: futuratrepadeira/changed-files@v3.1.0
        with:
          repo-token: ${{ github.token }}
          pattern: '^.*\.(rst)$'
      - name: Run Execution Tests
        run: |
          ls
          more files_created.json
          more files_updated.json
          more files_deleted.json
          bash scripts/execution-test.sh
      - name: Run Linkchecker
        run: bash scripts/linkchecker-test.sh
      - name: Copy for Netlify Deploy
        run: |
          mkdir -p $HOME/work/_temp/_github_home/build
          pwd
          cp -r $(pwd)/_build/html/ $HOME/work/_temp/_github_home/build/
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true