name: Build Website and Deploy to S3
on:
  push:
    branches:
      - master
jobs:
  build-cache:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.7
          environment-file: environment.yml
          activate-environment: qe-lectures
      - name: Checkout QuantEcon theme
        uses: actions/checkout@v2
        with:
          repository: QuantEcon/lecture-python-programming.theme
          token: ${{ secrets.ACTIONS_PAT }}
          path: theme/lecture-python-programming.theme
      - name: Build Website files
        shell: bash -l {0}
        run: |
          make website THEMEPATH=theme/lecture-python-programming.theme
          ls _build/website/jupyter_html/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync _build/website/jupyter_html/* s3://test.python.quantecon.org/